### ISSUE TITLE
Utilisé Yarn au lieu de Npm

### ISSUE THREAD

**Issue by follyjohn** [UTBM-FISA-TutoredProject/Frontend#1]
# Utilisé Yarn au lieu de Npm

Yarn est plus performant, plus sécurisé, maintenue par facebook et bien taillé pour le dev React.

Une recherche google vous le confirmera.

<https://phoenixnap.com/kb/yarn-vs-npm>

**Comment by Valentin271** [comment]
Je n'ai pas de problème à utilisé Yarn plutot que npm, j'ai utilisé npm par habitude.

Je pense que ça ne genera personne, de plus avec docker le changement est facile.
