### ISSUE TITLE
Désigner un référent d'équipe frontend.

### ISSUE THREAD

**Issue by kilian-goetz** [UTBM-FISA-TutoredProject/Frontend#4]
Bonjour @UTBM-FISA-TutoredProject/frontend-engineers,

Comme pour toutes les autres teams j'ouvre une issue pour définir un référent d'équipe.

Qu'est-ce qu'un référent d'équipe ? Un référent d'équipe est une personne désigné au titre de représentant de son équipe. Il a en charge le maintien du suivi du projet de son équipe, il aide les personnes de son équipes à se former sur les technologies utilisées, il est responsables des review de code, il participe aux réunions inter-équipes et communique régulièrement sur les avancés de son équipe.

Que faut-il faire pour devenir référent d'équipe ? Il suffit de poster sa candidature dans l'issue. Si une seule personne se présente, elle sera automatiquement désigné. Si plusieurs personnes se présentent, un vote aura lieux. Si aucune personne ne se présente, l'issue restera ouverte tant que personne ne se désigne. Une fois qu'une personne se désigne l'issue sera fermé 24h après la première candidature.

Quel profil pour un référent d'équipe ? Il faut de préférence une personne maîtrisant les technologies employées dans son équipe. De surcroît il doit avoir une bonne maîtrise de Github ou à défaut contacter le référent Github pour lui expliqué. La personne qui se présente à un sens des responsabilités et aime partager son savoir.

❗ Attention Un référent d'équipe n'est pas un chef, c'est un représentant, de fait il ne donne pas d'ordre et sa voix vaut autant qu'un autre membre de l'équipe. ❗

Avantage d'un référent d'équipe : Cela permet d'expérimenter le management.
Inconvénient : Cela incombe plus de travail.

Si vous avez besoin de plus d'informations concernant les postes de référents d'équipes n'hésitez pas à poser vos questions en commentaire de cette issue 😄,

Bonne journée à tous et à toutes.

**Comment by Valentin271** [comment]
Je veux bien me désigner.

J'ai déjà gérer des projets (entreprise ou étudiant) et j'ai 2 ans d'expérience React, je connais également un peu MUI.

**Comment by kilian-goetz** [comment]
@Valentin271,

Ok c'est noté ! Si personne d'autre ne se présente d'ici le **15/12/2022 (Format français) à 9h25 CEST** tu sera automatiquement désigné référent de l'équipe frontend.

**Comment by Valentin271** [comment]
L'organisation des équipes ayant été modifiée, il n'y a plus d'équipe frontend ni de référent associé.

Pour en savoir plus, voir [la documentation](https://neighbook.github.io/Documentation/#/organisation).
